kind: Service
apiVersion: v1
metadata:
  name: nginx-{{ .Values.deployment.name }}
  labels:
    app: ngin{{ .Values.deployment.name }}x
spec:
  selector:
    app: {{ .Values.deployment.name }}
  type: {{ .Values.service.type }}
  ports:
  - name: http-80
    port: 80
    targetPort: 80