apiVersion: v1
kind: Pod
metadata:
  name: test-pod
  namespace: workshop
  labels:
    app: test
spec:
  restartPolicy: Never # Always, OnFailure, Never
  containers:
    - name: busybox
      image: busybox
      imagePullPolicy: IfNotPresent # IfNotPresent, Always, Never
      resources:
        requests:
          memory: "64Mi"
          cpu: "50m"
        limits:
          memory: "128Mi"
          cpu: "100m"
      args:
        - bin/sh
        - -c
        - ls; sleep 3600
